server {
    server_name  crypto.pozdniakov.pro;

    location / {
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;

        proxy_pass                  http://localhost:8888;
        proxy_read_timeout     90;
    }

    error_log   /var/log/nginx/crypto_pozdniakov_pro_error.log error;
    access_log  /var/log/nginx/crypto_pozdniakov_pro_access.log;
 }
