[program:create_orders]
command=php -dmemory_limit=1G /app/bin/console rabbitmq:consumer -m 100 create_orders --env=dev -vv
process_name=create_orders%(process_num)02d
numprocs=1
directory=/tmp
autostart=true
autorestart=true
startsecs=3
startretries=10
user=www-data
redirect_stderr=false
stdout_logfile=/app/var/log/supervisor.create_orders.out.log
stdout_capture_maxbytes=1MB
stderr_logfile=/app/var/log/supervisor.create_orders.error.log
stderr_capture_maxbytes=1MB
